### PR TITLE
feat(table): add table component

### PR DESCRIPTION
**Pull request by ding-js**
a table component support sort, selection, search and so on based rc-table

BREAKING CHANGE: extract styles to react-components.css instead of js string

[demo](https://tradeshift.github.io/react-components/#/Components/Table)

### CODE REVIEW

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.0.0 (https://github.com/Tradeshift/react-components/compare/v2.0.1...v3.0.0) (2019-08-16)

### Features

 - table: add table component (211adbb (https://github.com/Tradeshift/react-components/commit/211adbb))

### BREAKING CHANGES

 - table: extract styles to react-components.css instead of js string

**Comment by KanonWang** [comment]
这个当初做的时候和@Chris-Xie 讨论过， 还是把css留在js里面，像这个一样https://github.com/Tradeshift/document-components

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.0.0 (https://github.com/Tradeshift/react-components/compare/v2.0.1...v3.0.0) (2019-08-16)

### Features

 - table: add table component (191ca8a (https://github.com/Tradeshift/react-components/commit/191ca8a))

### BREAKING CHANGES

 - table: extract styles to react-components.css instead of js string

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.0.0 (https://github.com/Tradeshift/react-components/compare/v2.0.1...v3.0.0) (2019-08-16)

### Features

 - table: add table component (3da7c29 (https://github.com/Tradeshift/react-components/commit/3da7c29))

### BREAKING CHANGES

 - table: extract styles to react-components.css instead of js string

**Comment by Chris-Xie** [comment]
table的样式看起来和标准TS UI的好像有点差异

**Comment by ding-js** [comment]
> table的样式看起来和标准TS UI的好像有点差异

表头字号和大小写修复了。
这个 demo 块的边框需要忽略一下，还有别的地方有差异吗？

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.0.0 (https://github.com/Tradeshift/react-components/compare/v2.0.1...v3.0.0) (2019-08-16)

### Features

 - table: add table component (9475941 (https://github.com/Tradeshift/react-components/commit/9475941))

### BREAKING CHANGES

 - table: extract styles to react-components.css instead of js string

**Comment by ding-js** [comment]
> 这个当初做的时候和@Chris-Xie 讨论过， 还是把css留在js里面，像这个一样https://github.com/Tradeshift/document-components

刚才和 @Chris-Xie 讨论了一下，还是把样式提取出来，这是个 breaking change，升级版本后需要在入口引用样式文件。

**Pull request merged**
