### PR TITLE
feat(pagination): add new component pagination

### PR DESCRIPTION
**Pull request by ding-js**
[Demo](https://tradeshift.github.io/react-components/#/Components/Pagination)

### CODE REVIEW

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-20)

### Features

 - pagination: add new component pagination (658264d (https://github.com/Tradeshift/react-components/commit/658264d))

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-20)

### Features

 - pagination: add new component pagination (8485f04 (https://github.com/Tradeshift/react-components/commit/8485f04))

**Comment by Chris-Xie** [comment]
pageSize 和 total和分页没有关系。分页器只关心一共多少页，当前第几页。

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-20)

### Features

 - pagination: add new component pagination (ef386a8 (https://github.com/Tradeshift/react-components/commit/ef386a8))

**Comment by ding-js** [comment]
> pageSize 和 total和分页没有关系。分页器只关心一共多少页，当前第几页。

修改 api 与 ts-ui 保持一致

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-20)

### Features

 - pagination: add new component pagination (7d7975e (https://github.com/Tradeshift/react-components/commit/7d7975e))

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-20)

### Features

 - pagination: add new component pagination (5e2b209 (https://github.com/Tradeshift/react-components/commit/5e2b209))

**Comment by Chris-Xie** [comment]
样式不太一样，字体好像要加粗

**Comment by ding-js** [comment]
> 样式不太一样，字体好像要加粗

修复字体样式的问题
修复 '...' 宽度计算居中位置
image

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-20)

### Features

 - pagination: add new component pagination (af7f36b (https://github.com/Tradeshift/react-components/commit/af7f36b))

**Comment by Chris-Xie** [comment]
paging

prev button似乎逻辑有点问题。

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-21)

### Features

 - pagination: add new component pagination (3ee50ce (https://github.com/Tradeshift/react-components/commit/3ee50ce))

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

# 3.1.0 (https://github.com/Tradeshift/react-components/compare/v3.0.0...v3.1.0) (2019-08-21)

### Features

 - pagination: add new component pagination (341a722 (https://github.com/Tradeshift/react-components/commit/341a722))

**Pull request merged**
